# Generated by Django 5.2.1 on 2025-06-06 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the service category (e.g., Plumbing, Electrical, Cleaning).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional: A brief description of the service category.')),
                ('icon', models.ImageField(blank=True, help_text='Optional: Icon image for the category.', null=True, upload_to='category_icons/')),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderProfile',
            fields=[
                ('user', models.OneToOneField(help_text='The user account for this service provider.', limit_choices_to={'is_provider': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(blank=True, help_text='Official business name, if different from username.', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='A short biography or description of the provider/services.')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=20)),
                ('services_offered', models.ManyToManyField(blank=True, help_text='Categories of services offered by this provider.', related_name='providers', to='api.servicecategory')),
            ],
        ),
    ]
