# Generated by Django 5.2.1 on 2025-06-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='room_identifier',
            field=models.CharField(db_index=True, default='', help_text="Identifier for the chat room (e.g., 'booking_123', 'chat_user3_user5').", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='The booking this chat message is related to, if any (for booking-specific chats).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='api.booking'),
        ),
    ]
