# Generated by Django 5.2.1 on 2025-08-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_serviceproviderprofile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='A profile picture for the service provider.', null=True, upload_to='provider_pictures/'),
        ),
    ]
