# Generated by Django 5.2.1 on 2025-08-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_serviceproviderprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='icon',
        ),
    ]
