# Generated by Django 5.2.1 on 2025-08-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_servicecategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='category_image',
            field=models.ImageField(blank=True, help_text='An image representing the service category (for landing page, etc.).', null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.ImageField(blank=True, help_text='Optional: Icon image for the category.', null=True, upload_to='category_icons/'),
        ),
    ]
