# Generated by Django 5.2.1 on 2025-08-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_servicecategory_category_image_servicecategory_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Optional: Icon image for the category.', max_length=100, null=True),
        ),
    ]
